### ISSUE TITLE
Fill empty slots

### ISSUE THREAD

**Issue by SpiziTV** [MherZaqaryan/BedWars1058-Cosmetics-Issues#1]
Add the possibility the fill empty slots with Glass Pane per exemple

Maybe add in the config a way to set something like :
fill-empty-slots: true
or
fill-empty-slots: false

And another line with
empty-slots-item: WHITE_STAINED_GLASS_PANE

Thanks in advance :)

**Comment by MherZaqaryan** [comment]
This feature request is accepted and will be available in the next update!

**Comment by MherZaqaryan** [comment]
This feature has been implemented.
