### ISSUE TITLE
TPS drop during Cold Snap Dance

### ISSUE THREAD

**Issue by NeosKing108** [MherZaqaryan/BedWars1058-Cosmetics-Issues#10]
**Describe the bug**
When you use Cold Snap dance during the dance server TPS drop fast

**How to reproduce**
1. Select Cold Snap dance
2. Win a game
3. during the dance the server TPS drop

**Screenshots**
Yt Video: https://youtu.be/53x1IFsK4Lo

**Server Information (please complete the following information):**
 - OS: [Linux]
 - Server Software: [Paper]
 - Software Version: [1.8.8]
 - BedWars1058 Version: [22.3.4]
 - Cosmetics Addon: [1.0.0]

**Additional context**
Server's informations
- Ryzen 9 3900x (6 core)
- 16gb ram DDR4 (3200MHz) -> 14 dedicated to server

**Comment by MherZaqaryan** [comment]
Improved the performance of this victory dance, it'll be available in the next 1.0.1 version.
