### ISSUE TITLE
[Bug] Trail items do not disappear after throwing a fireball

### ISSUE THREAD

**Issue by ImYenil** [MherZaqaryan/BedWars1058-Cosmetics-Issues#100]
**Describe the bug**
Trail items do not disappear after throwing a fireball

**How to reproduce**
1. get fireball
2. throw fireball
3. get issue

**Screenshots**
![image](https://user-images.githubusercontent.com/85287520/235468613-6dcb2011-ebd6-4a84-a6d8-9a4435d0f1ea.png)

**Server Information (please complete the following information):**
 - OS: [e.g. Linux, Windows] Windows 
 - Server Software: [e.g. Paper, Spigot] Paper
 - Software Version: [e.g. 1.8.9] 1.8.9
 - BedWars1058 Version: [e.g. 21.10.1] 23.3-SNAPSHOT
 - Cosmetics Addon: [e.g. 1.1.1] 1.1.2

**Comment by MherZaqaryan** [comment]
This issue is already fixed, and will be available in the next update!
