### ISSUE TITLE
[Bug] A bug where the player could use the spray without directly clicking on the item frame

### ISSUE THREAD

**Issue by ImYenil** [MherZaqaryan/BedWars1058-Cosmetics-Issues#101]
**Describe the bug**
A bug where the player could use the spray without directly clicking on the item frame

**How to reproduce**
1. Throwing a TNT or fireball around an item frame triggers the spray

**Screenshots**
here viedo

https://user-images.githubusercontent.com/85287520/235469683-03227e3f-fb2e-4f4e-93dc-383440a56a37.mp4

**Server Information (please complete the following information):**
 - OS: [e.g. Linux, Windows] Windows
 - Server Software: [e.g. Paper, Spigot] Paper
 - Software Version: [e.g. 1.8.9] 1.8.9
 - BedWars1058 Version: [e.g. 21.10.1] 23.3-SNAPSHOT
 - Cosmetics Addon: [e.g. 1.1.1] 1.2.2

**Comment by ImYenil** [comment]
Any eta?

**Comment by MherZaqaryan** [comment]
Thanks for reporting! This issue is fixed, and will be available in the next update!
