### ISSUE TITLE
[Bug] Error GameEndEvent on console

### ISSUE THREAD

**Issue by Squesly** [MherZaqaryan/BedWars1058-Cosmetics-Issues#102]
**Describe the bug**

**How to reproduce**
1. Play game
2. Wait until game end

**Server Information (please complete the following information):**
 - OS: Ubuntu (Pterodactyl)
 - Server Software: PaperSpigot
 - Software Version: 1.8.8
 - BedWars1058 Version: 22.7
 - Cosmetics Addon: 1.1.2

 Error: 
[message.txt](https://github.com/MherZaqaryan/BedWars1058-Cosmetics-Issues/files/11463005/message.txt) <---- HERE

**Comment by MherZaqaryan** [comment]
Thanks for reporting! This issue is fixed, and the fix will be available in the next update.
