### ISSUE TITLE
[Bug] Category placeholder doesn't show up with the player's language in the cosmetic search menu

### ISSUE THREAD

**Issue by AstralStalyer** [MherZaqaryan/BedWars1058-Cosmetics-Issues#104]
**Describe the bug**
In the search menu, players can't see the content in the predetermined language file.

**How to reproduce**
1. Open the Main Menu
2. Search
3. That way, you can see that the special effects category is not displayed as scheduled

**Screenshots**
![1](https://github.com/MherZaqaryan/BedWars1058-Cosmetics-Issues/assets/113582475/370640d0-0ea1-4c66-afbc-bc90a1eeb4a8)
![2](https://github.com/MherZaqaryan/BedWars1058-Cosmetics-Issues/assets/113582475/54e519d2-af96-461e-9b20-87db000ef08c)

**Server Information (please complete the following information):**
 - OS: [Windows]
 - Server Software: [Spigot]
 - Software Version: [1.8.9]
 - BedWars1058 Version: [22.7]
 - Cosmetics Addon: [1.1.2]

**Additional context**

**Comment by MherZaqaryan** [comment]
This issue is already fixed and will be available in the next update!
