### ISSUE TITLE
[Bug] Victory Dances Cosmetics Bug

### ISSUE THREAD

**Issue by AlHadiHabib** [MherZaqaryan/BedWars1058-Cosmetics-Issues#105]
I found a bug in the victory dance cosmetic. After winning a match, a dragon gets spawned in this cosmetic. When a player is sitting on the dragon, they get damaged by the fireball, and if the dragon enters a building, the player gets damaged. Additionally, sometimes the player dies.

**Comment by MherZaqaryan** [comment]
This issue will be fixed when BedWars1058 merges this pull request https://github.com/andrei1058/BedWars1058/pull/474. Additionally, [BedWars2023](https://github.com/tomkeuper/BedWars2023) support will be added in the next update, which has that same pull request already merged, and thus will fix the issue.
