### ISSUE TITLE
[Feature Request] Give specific cosmetics without giving String Permission per user

### ISSUE THREAD

**Issue by iiAhmedYT** [MherZaqaryan/BedWars1058-Cosmetics-Issues#108]
**Is your feature request related to a problem? Please describe.**
Yes, I tried to make a loot system. I can't give cosmetics without giving away perms for ALL servers

**Describe the solution you'd like**
I would like to give cosmetics to players without giving them a per user permission. Instead just do something like: /cosmetics give {player} {category} {cosmetic}

**Additional context**
![image](https://github.com/MherZaqaryan/BedWars1058-Cosmetics-Issues/assets/61851106/743c7b0e-c986-4734-aa07-d8fd5ac880fb)

**Comment by MherZaqaryan** [comment]
Thanks for the suggestion! Your feature request is accepted and will be considered for the next update.

**Comment by MherZaqaryan** [comment]
This feature request has been implemented, and it will be available in the next update!
