### ISSUE TITLE
[Feature Request] More placeholder replacements

### ISSUE THREAD

**Issue by iiAhmedYT** [MherZaqaryan/BedWars1058-Cosmetics-Issues#109]
**Is your feature request related to a problem? Please describe.**
Please replace these placeholders in the ingame kill messages
I want to replace the {victim} placeholder with "{PlayerColor}{PlayerNameUnformatted}" instead of "{PlayerColor}{PlayerName}"

same for {killer}

My request is to make them customizable
**Describe the solution you'd like**
Add a replacer in the messages file

**Describe alternatives you've considered**
I replaced those placeholders using packets, wasn't a good idea and caused problems with most other messages

**Comment by MherZaqaryan** [comment]
Thanks for the suggestion! Your feature request is accepted and will be considered for the next update.

**Comment by MherZaqaryan** [comment]
This feature request is implemented and it will be available in the next update!

Among with `{victim}`, `{killer}`, and `{destroyer}` I've added new ones for each:
- `{victimName}` - Gets replaced by the victim name.
- `{victimTeamColor}` - Gets replaced by the victim's team color (e.g. **&a**, **&c**).
- `{killerName}` - Gets replaced by the killer name.
- `{killerTeamColor}` - Gets replaced by the killer's team color (e.g. **&a**, **&c**).
- `{destroyerName}` - Gets replaced by the bed destroyer name.
- `{destroyerTeamColor}` - Gets replaced by the bed destroyer's team color (e.g. **&a**, **&c**).
