### ISSUE TITLE
Cosmetic reset or remove

### ISSUE THREAD

**Issue by NeosKing108** [MherZaqaryan/BedWars1058-Cosmetics-Issues#11]
**Is your feature request related to a problem? Please describe.**
No, is not releated to a problem

**Describe the solution you'd like**
A command to remove the selected cosmetic for every category
Ex. /cosmetic remove <PlayerName>

**Describe alternatives you've considered**

**Additional context**

**Comment by MherZaqaryan** [comment]
Please give more information about your feature request.

**Comment by NeosKing108** [comment]
> Please give more information about your feature request.

when you type: "/cosmetic reset <player>" it sets all player's cosmetics categories to default

**Comment by MherZaqaryan** [comment]
#7
