### ISSUE TITLE
[Bug] Victory Dance

### ISSUE THREAD

**Issue by ManiXD** [MherZaqaryan/BedWars1058-Cosmetics-Issues#110]
**Describe the bug**
Whenever a player wins in a game and gets toy stick for their victory dance it remains in their inventory after they leave the arena and return to the same arena for the next game.

**Server Information (please complete the following information):**
 - OS: Windows
 - Server Software: Spigot
 - Software Version: 1.8.8
 - BedWars1058 Version: 23.12.2
 - Cosmetics Addon: 1.1.2

**Comment by MherZaqaryan** [comment]
This issue is fixed, and the fix will be available in the next update!
