### ISSUE TITLE
Toy Stick "Enchanted" Option doesnt work

### ISSUE THREAD

**Issue by vicente131313131** [MherZaqaryan/BedWars1058-Cosmetics-Issues#112]
**Describe the bug**
The toy stick enchanted option on the victory-dances configuration doesnt work

**Screenshots**
![image](https://github.com/MherZaqaryan/BedWars1058-Cosmetics-Issues/assets/145242890/751056b9-da04-43a5-b047-5669eb36af3d) 
![image](https://github.com/MherZaqaryan/BedWars1058-Cosmetics-Issues/assets/145242890/c93fee14-56a1-4508-86ab-fac2b29320ae)

**Server Information:**
 - OS: Windows
 - Server Software: Paper
 - Software Version: 1.8.8
 - BedWars1058 Version: 22.3.4
 - Cosmetics Addon: 1.1.3

**Comment by MherZaqaryan** [comment]
This issue is fixed, and the fix will be available in the next update!
