### ISSUE TITLE
[Bug] mob shopkeeper NPCs silent doesn't apply

### ISSUE THREAD

**Issue by ImYenil** [MherZaqaryan/BedWars1058-Cosmetics-Issues#117]
**Describe the bug**
mob shopkeeper NPCs silent doesn't apply

**Server Information (please complete the following information):**
 - OS: [e.g. Linux, Windows] Windows
 - Server Software: [e.g. Paper, Spigot] Paper
 - Software Version: [e.g. 1.8.9] 1.8.9
 - BedWars1058 Version: [e.g. 21.10.1] 23.2.1
 - Cosmetics Addon: [e.g. 1.1.1] 1.2.0

**Comment by MherZaqaryan** [comment]
This tick
