### ISSUE TITLE
Better Config structure

### ISSUE THREAD

**Issue by Xxyuri2005xX** [MherZaqaryan/BedWars1058-Cosmetics-Issues#12]
**Is your feature request related to a problem? Please describe.**
With Bedwars1058 Cosmetics you have 1 only big config file of 2000 lines which contains all the things.

**Describe the solution you'd like**
A decicated folder named: "Cosmetic-Config or Cosmetics" which contains 10 different config files named by cosmetic category (like: bed-destroy.yml contains bed destroy effects).
the config should obviously continue to support the manual add feature for those cosmetics that support it.

**Describe alternatives you've considered**

**Additional context**

**Comment by MherZaqaryan** [comment]
This feature is accepted, has already been implemented, and should be available in the next update!
