### ISSUE TITLE
[1.16.5] crash on startup 

### ISSUE THREAD

**Issue by neziw** [MherZaqaryan/BedWars1058-Cosmetics-Issues#17]
**Describe the bug**
Plugin crash while server starting up

**How to reproduce**
1. Download Cosmetics plugin
2. Upload to plugins folder
3. Start server with version 1.16.5 (Paper/Purpur)

**Screenshots**

**Server Information (please complete the following information):**
 - OS: [e.g. Linux, Windows] LINUX (Debian)
 - Server Software: [e.g. Paper, Spigot] git-Purpur-1171 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
 - Software Version: [e.g. 1.8.9] 1.16.5
 - BedWars1058 Version: [e.g. 21.10.1] BedWars Proxy 1.2.4
 - Cosmetics Addon: [e.g. 1.1.1] 1.0.0

**Additional context**
Logs: https://www.toptal.com/developers/hastebin/ekefixipoh.sql

**Comment by MherZaqaryan** [comment]
This issue is already fixed and should be available in the next update!
