### ISSUE TITLE
bed destroy

### ISSUE THREAD

**Issue by Propants05** [MherZaqaryan/BedWars1058-Cosmetics-Issues#19]
**Describe the bug**
the effects of destruction of the bed does not go

**Screenshots**
![image](https://user-images.githubusercontent.com/85504551/165118591-d2cd4978-74d0-4bc9-9847-1bdb1a700cd4.png)

**Server Information (please complete the following information):**
 - OS: linux
 - Server Software: paper
 - Software Version: 1.12.2
 - BedWars1058 Version: 21.10.1
 - Cosmetics Addon:  1.0.0

**Comment by MherZaqaryan** [comment]
This was not an issue, the config was broken.
