### ISSUE TITLE
Cosmetic Error

### ISSUE THREAD

**Issue by LeafPlays** [MherZaqaryan/BedWars1058-Cosmetics-Issues#21]
**Describe the bug**
Plugin crash while server starting up

**How to reproduce**
1. Download Cosmetics plugin
2. Upload to plugins folder
3. Start server with version 1.8.8

**Screenshots**

**Server Information (please complete the following information):**
 - OS: Linux (Ubuntu)
 - Server Software: git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
 - Software Version: 1.8.8
 - BedWars1058 Version: 22.3.4
 - Cosmetics Addon: 1.0.0

**Additional context**
Log: https://pastebin.com/jQSggcgj

**Comment by LeafPlays** [comment]
2.0.16

**Comment by MherZaqaryan** [comment]
Please try updating or restarting your server!

**Comment by LeafPlays** [comment]
Works now thanks
