### ISSUE TITLE
[Bug] Shopkeeper Skin issue

### ISSUE THREAD

**Issue by NeosKing108** [MherZaqaryan/BedWars1058-Cosmetics-Issues#22]
**Describe the bug**
When you use a custom shopkeeper skin, on game start or sometimes when you die, the shopkeeper skin "unloads" (converts from selected skin to alex)

**How to reproduce**
1. Select a shopkeeper skin
2. Join a Game
3. Game Starts
4. Shopkeeper can spawn already unloaded or when you die it unloads

**Screenshots**
Youtube video: https://youtu.be/Il_TVCpaXUQ

**Server Information (please complete the following information):**
 - OS: Linux
 - Server Software: Paper
 - Software Version: 1.8.8
 - BedWars1058 Version: 22.3.4
 - Cosmetics Addon: 1.0.0
 
**Additional context**

**Comment by MherZaqaryan** [comment]
Thanks for reporting. This issue is more like Citizens, I've tried a couple of fixes but unfortunately couldn't solve it.
