### ISSUE TITLE
water bucket issue

### ISSUE THREAD

**Issue by GyroGyro** [MherZaqaryan/BedWars1058-Cosmetics-Issues#23]
**Describe the bug**
when you use the bucket of water you cannot place everywhere as normal but you can only use the water in places where it would not be possible such as on the generator or in the spawn protection area

**How to reproduce**
1. buy a water bucket
2. try to place the water everywhere
3. then you can see that you cannot place the water everywhere but only near the protected area (like: generators, shopkeepers and spawn) 

**Server Information (please complete the following information):**
 - OS: Linux
 - Server Software: Paper
 - Software Version: 1.8.9
 - BedWars1058 Version: 22.3.4
 - Cosmetics Addon: 1.0.0

**Additional context**
removing the Cosmetics plugin solves the problem

**Comment by MherZaqaryan** [comment]
This issue is already fixed and will be available in the next update!
