### ISSUE TITLE
Citizens hologram spam

### ISSUE THREAD

**Issue by kimovoid** [MherZaqaryan/BedWars1058-Cosmetics-Issues#24]
**Describe the bug**
When you use a NPC shopkeeper, the console spams "[ERROR]: [Citizens] More hologram NPCs than lines for ID ...". This probably causes the NPC holograms to appear darker (duplicate holograms).

**How to reproduce**
1. Open cosmetics menu
2. Select a NPC shopkeeper
3. Go ingame and check the console

**Screenshots**
![image](https://user-images.githubusercontent.com/29529059/166103616-a182a381-7c0c-45d8-adaa-70cfb0ab2a2c.png)

**Server Information (please complete the following information):**
 - OS: Debian 10
 - Server Software: Paper
 - Software Version: 1.8.8
 - BedWars1058 Version: 22.3
 - Cosmetics Addon: 1.0.0

**Additional context**
None

**Comment by MherZaqaryan** [comment]
This issue fixes when you update your Citizens!
