### ISSUE TITLE
Toy stick cosmetic not working

### ISSUE THREAD

**Issue by kimovoid** [MherZaqaryan/BedWars1058-Cosmetics-Issues#25]
**Describe the bug**
The toy stick victory dance does not work and only gives a console error.

**How to reproduce**
1. Select the toy stick victory dance
2. Win a game
3. Right click the toy stick and check console

**Screenshots**
![image](https://user-images.githubusercontent.com/29529059/166103797-213faf9f-3041-4de9-88d6-eca750a39cc3.png)

**Server Information (please complete the following information):**
 - OS: Debian 10
 - Server Software: Paper
 - Software Version: 1.8.8
 - BedWars1058 Version: 22.3
 - Cosmetics Addon: 1.0.0

**Additional context**
None

**Comment by MherZaqaryan** [comment]
I've tried to reproduce it but haven't got any issues please make sure to post the error with the latest version and as a text.
