### ISSUE TITLE
Spray left-click

### ISSUE THREAD

**Issue by kimovoid** [MherZaqaryan/BedWars1058-Cosmetics-Issues#26]
**Is your feature request related to a problem? Please describe.**
Not really a problem. But on hypixel I'm used to left clicking the item frame to use a spray, so being limited to only right-click is a bit weird.

**Describe the solution you'd like**
Enabling the players to left-click the item frames to use a spray.

**Comment by MherZaqaryan** [comment]
This suggestion is accepted and will be implemented.

**Comment by MherZaqaryan** [comment]
This feature is already implemented, and will be available in the next update!

**Comment by MherZaqaryan** [comment]
This feature request has already been implemented and will be available in the next update!
