### ISSUE TITLE
Add option for buying

### ISSUE THREAD

**Issue by SpiziTV** [MherZaqaryan/BedWars1058-Cosmetics-Issues#3]
I would like an option to enable/disable buying cosmetics

In my case, i want to remove the buying cosmetics function 
I just want that the player have to open my mysterybox to obtain cosmetics

So add an option like :
buy-cosmetics: true
or 
buy-cosmetics: false

Thanks in advance

**Comment by MherZaqaryan** [comment]
This feature request is accepted, and should be available in the next update!
