### ISSUE TITLE
Rank Discount

### ISSUE THREAD

**Issue by lunoxxofficial** [MherZaqaryan/BedWars1058-Cosmetics-Issues#30]
**Make it so we will be able to make discounts for cosmetics purchaces based on their rank**
Ex-
Vip - 10% off
mvp - 20% off
Everything should be configurable and player with reqired permission has it

In config 
```
Discount
  vip
   permission - bw.discount.vip
   discount presentage - 10
```
 

(gadget menu has this feature in their plugin)

**Comment by MherZaqaryan** [comment]
This feature request is accepted.

**Comment by MherZaqaryan** [comment]
This feature request is implemented and will be available in the next update!
