### ISSUE TITLE
PROBLEM WHEN USING SNOWBALL RAIN (OR DERIVATIVES)

### ISSUE THREAD

**Issue by EvilG-MC** [MherZaqaryan/BedWars1058-Cosmetics-Issues#32]
**Describe the bug**
When launching a projectile with a specific effect (Snowball Rain), the console starts to launch an error.

**How to reproduce**
1. Open the Cosmetics Menu
2. Select Projectile Trails
3. Search the Snowball Rain trail
4. Enter in a game
5. Launch a fireball or snowball
6. See the result.

**Screenshots**
![image](https://user-images.githubusercontent.com/71156616/168859877-2c585148-f7e4-4712-9559-506e5cffc0ac.png)

**Server Information:**
 - OS: Linux
 - Server Software: PaperMC
 - Software Version: 1.16.5
 - BedWars1058 Version: 22.3-SNAPSHOT (Github compiled version)
 - Cosmetics Addon: 1.0.0 (Discord version)

**Comment by MherZaqaryan** [comment]
This issue has already been fixed and should be available in the next update!
