### ISSUE TITLE
ShopKeepers issue with player in spectator mode

### ISSUE THREAD

**Issue by GyroGyro** [MherZaqaryan/BedWars1058-Cosmetics-Issues#34]
**Describe the bug**
The shopkeepers turn around following the spectators.
if a spectator approaches a shopkeeper, the shopkeeper will move following the spectator.

**How to reproduce**
1. start a game and join as spectator
2. approach a shopkeeper

**Server Information (please complete the following information):**
 - OS: Linux
 - Server Software: Paper
 - Software Version: 1.8.9
 - BedWars1058 Version: 22.3.4
 - Cosmetics Addon: 1.0.0

**Comment by MherZaqaryan** [comment]
This issue has been already fixed and should be available in the next update!
