### ISSUE TITLE
Projectile Trails Issue

### ISSUE THREAD

**Issue by GyroGyro** [MherZaqaryan/BedWars1058-Cosmetics-Issues#35]
**Describe the bug**
If I use fireballs in a world other than the arena, such as bedwars practice arenas the fireball will do the selected effect.

**How to reproduce**
1. Join non-game/lobby Worlds (without lobby protection)
2. Select a projectile trail (skip that step if there is already a trail enabled)
3. Launch a fireball or an arrow in the air
4. Watch projectile trail

**Screenshots**
https://imgur.com/SItyJKT.png
https://imgur.com/KvC5cH9.png (Screen from Xx_yuri2005_xX)

**Server Information (please complete the following information):**
 - OS: Linux
 - Server Software: Paper Fork (NachoSpigot)
 - Software Version: 1.8.9
 - BedWars1058 Version: 22.3-SNAPSHOT (compiled form github)
 - Cosmetics Addon: 1.0.0

**Additional context**
Server Type: MultiArena

**Comment by MherZaqaryan** [comment]
This issue has been already fixed and should be available in the next update!
