### ISSUE TITLE
[IMPORTANT] [BUG] the plugin does not start❌

### ISSUE THREAD

**Issue by haroldrc** [MherZaqaryan/BedWars1058-Cosmetics-Issues#36]
**Describe the bug**
the plugin when it starts from this error https://pastebin.com/FpfS34Ru

**How to reproduce**
1. put the plugin in the folder
2. Then that...
3. Will result in...

**Screenshots**

**Server Information (please complete the following information):**
 - OS: Linux
 - Server Software: Paper
 - Software Version: 1.8.9
 - BedWars1058 Version: 22.3.4
 - Cosmetics Addon: 1.01

**Additional context**

**Comment by MherZaqaryan** [comment]
Please confirm your identity on Discord!

**Comment by haroldrc** [comment]
I did it
