### ISSUE TITLE
MySQL 8 connection

### ISSUE THREAD

**Issue by EmilianoMari** [MherZaqaryan/BedWars1058-Cosmetics-Issues#38]
**Describe the bug**
The plugin is not finding a global mysql variable not available from mysql version 8.0

**How to reproduce**
1. Use mysql 8
2. Configure the main bedwars plugin to use the mysql server
3. Add the addon plugin to the server

**Server Information (please complete the following information):**
 - OS: Linux 
 - Server Software: Paper
 - Software Version: 1.8.8
 - BedWars1058 Version: 22.3
 - Cosmetics Addon: 1.0.1

**Additional context**
https://pastebin.com/raw/FpfS34Ru

Also the bedwars1058 plugin has the same problem, we solved that adding the mysql-connector-java dependency and explicitly setting the driver class used by Hikari to com.mysql.cj.jdbc.Driver

**Comment by MherZaqaryan** [comment]
I don't think BedWars1058 solved the issue in that way.
