### ISSUE TITLE
Translatable message increase

### ISSUE THREAD

**Issue by PixelEast** [MherZaqaryan/BedWars1058-Cosmetics-Issues#42]
I noticed that a part of the plugin menu could not be translated
![image](https://user-images.githubusercontent.com/30312760/178157595-0b0e63df-060f-4398-8052-520679bd8c46.png)
![image](https://user-images.githubusercontent.com/30312760/178157604-c11b5db9-1129-4d8c-abe2-91f94c1600bb.png)
I can't find anywhere to modify this category
I hope can add language modification support for this

**Comment by MherZaqaryan** [comment]
This feature request has been already implemented and will be available in the next update!

**Comment by MherZaqaryan** [comment]
This feature request has been implemented, and the following update will include it!
