### ISSUE TITLE
[Feature Request] Add a button to close menu in main cosmetics menu

### ISSUE THREAD

**Issue by UnitedCraft** [MherZaqaryan/BedWars1058-Cosmetics-Issues#44]
Hello, I would like this button to close the menu in the cosmetics main menu
![image](https://user-images.githubusercontent.com/79587189/182374903-93c8bca4-a2f9-47bd-b548-b6daec02403b.png)

**Comment by MherZaqaryan** [comment]
This suggestion is accepted, and there will be a way to set a `close` as a command there, so when you click on it, it will close the GUI.

**Comment by MherZaqaryan** [comment]
This feature request has been implemented and will be available in the next update.
