### ISSUE TITLE
Projectile Trails works in all worlds but not in arena

### ISSUE THREAD

**Issue by GyroGyro** [MherZaqaryan/BedWars1058-Cosmetics-Issues#46]
**Describe the bug**
Same issue of https://github.com/MherZaqaryan/BedWars1058-Cosmetics-Issues/issues/35
but now trails work in all worlds but not in arenas

**How to reproduce**
1) Join non-game/lobby Worlds (without lobby protection)
2) Select a projectile trail (skip that step if there is already a trail enabled)
3) Launch a fireball or an arrow in the air
4) Watch projectile trail
5) Now enter an arena and shoot an arrow, you will see that there will be no trails

**Screenshots**
https://www.youtube.com/watch?v=Td04peywMRM

**Server Information (please complete the following information):**
 - OS: Linux
 - Server Software: Paper Fork (NachoSpigot)
 - Software Version: 1.8.9
 - BedWars1058 Version: 22.3-SNAPSHOT (compiled form github)
 - Cosmetics Addon: 1.0.1

**Additional context**
Server Type: MultiArena

**Comment by MherZaqaryan** [comment]
This issue has already been fixed and will be fixed in the next update!
