### ISSUE TITLE
[Feature Request] Improve of toystick

### ISSUE THREAD

**Issue by foo1ishh** [MherZaqaryan/BedWars1058-Cosmetics-Issues#47]
In hypixel, the toy stick boost a little bit backward and smoother instead of just boosting upward. So I hope u can follow hypixel and change the toy stick to boost a little bit backward

**Comment by MherZaqaryan** [comment]
This feature request is accepted, I will make it configurable in the next update ~probably~.

**Comment by MherZaqaryan** [comment]
This feature has been implemented, and will be available in the next update
