### ISSUE TITLE
[Bug] NPCs

### ISSUE THREAD

**Issue by foo1ishh** [MherZaqaryan/BedWars1058-Cosmetics-Issues#48]
Server version: 1.8
The npc’s holograms bugged. When player select different languages. The hologram of NPCs of other team was not the Lang chosen.

**Comment by MherZaqaryan** [comment]
Thanks for reporting. Since I'm using Citizens to display those names, and there is no way to display custom holograms for each player I will probably go ahead and leave it on the default language selected from BedWars1058.

**Comment by MherZaqaryan** [comment]
This issue has already been resolved, and the following update will include it!
