### ISSUE TITLE
[Bug] Spray used sounds can be hear from many blocks away

### ISSUE THREAD

**Issue by Caily-E** [MherZaqaryan/BedWars1058-Cosmetics-Issues#56]
**Describe the bug**
when you throw a fireball, any projectiles, or hit with a bow from far away you can hear the spray sound, and only the player that triggered the spray can listen to that sound. 

1. buy any kind of projectiles like a fireball or even a bow and arrow
2. go further away from the ItemFrame and aim the projectile or bow and arrow at the item frame
3. you will be able to hear the sound even if you hit it from 64 blocks away, and people near spray won't hear the sound.

**Server Information (please complete the following information):**
 - OS: Linux
 - Server Software: CarbonSpigot
 - Software Version: 1.8.8
 - BedWars1058 Version: 22.7
 - Cosmetics Addon: 1.0.3 Beta
 
 **Additional context**
 Make it so people only near the item frame can hear the sound

**Comment by MherZaqaryan** [comment]
This issue is already fixed and will be available in the next update!
