### ISSUE TITLE
[Feature Request] Tab Complete for Cosmetics Set Command

### ISSUE THREAD

**Issue by Caily-E** [MherZaqaryan/BedWars1058-Cosmetics-Issues#57]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Tab Complete for /cosmetics set command to get the category and the cosmetic name

**Describe alternatives you've considered**
Tab Complete for at least category

**Comment by MherZaqaryan** [comment]
This feature request has been accepted and has already been implemented for subcommands `menu` and `set` (category and its cosmetics) and will be available in the next update

**Comment by MherZaqaryan** [comment]
This feature request has been accepted and has already been implemented for the subcommands menu and set (category and its cosmetics) and will be available in the next update.
