### ISSUE TITLE
[Bug] Incomplete Arguments Error

### ISSUE THREAD

**Issue by Caily-E** [MherZaqaryan/BedWars1058-Cosmetics-Issues#59]
**Describe the bug**
When you type the command /cosmetics set (Name) (category) without providing the last argument, the plugin throws an error as seen in the screenshots below.

**How to reproduce**
1. Join your server and write the command /cosmetics set (Name) (Category) without providing the last arguments.
2. Then you see the message "An internal error occurred while attempting to perform this command".

**Screenshots**
Usage:
https://imgur.com/jTjUipX
After:
https://imgur.com/PjUEpJm

**Server Information (please complete the following information):**
 - OS: Linux
 - Server Software: CarbonSpigot
 - Software Version: 1.8.8
 - BedWars1058 Version: 22.7
 - Cosmetics Addon: 1.0.3-BETA

**Comment by MherZaqaryan** [comment]
This issue has been fixed and will be available in the next update.
