### ISSUE TITLE
The cosmetics I selected before joining the game are not applied (serverType: BUNGEE)

### ISSUE THREAD

**Issue by DarkNinja00** [MherZaqaryan/BedWars1058-Cosmetics-Issues#6]
**Bug description**

(I apologize for my English but I use the translator)
The cosmetics I selected before joining the game are not applied (serverType: BUNGEE)
Before entering the games where bedwars1058 is located I am in the server lobby (where there is BedWarsProxy) I select the cosmetic and enter the game, once the game has started I have not applied the previously selected cosmetics, as if the cosmetics do not send the data in the databases in real time and are not applied.
This problem happens with all cosmetics

**How to reproduce**
1. Stay in the bedwars server lobby (where the BedWarsProxy plugin is)
2. Open the cosmetics menu
3. select all the cosmetics you want
4. Join a game of bedwars (so on a server where you have BedWars1058)
5. You will notice that the cosmetics have not been applied

**Screenshots**
![immagine](https://user-images.githubusercontent.com/73846191/164475138-796e48e1-2fc2-4a61-b00f-160e379c4d5f.png)

![immagine](https://user-images.githubusercontent.com/73846191/164476521-326f31ab-0c3f-43a5-be76-17db814decca.png)

**Server Information:**
 - Server Version: 1.8.8
 - BedWars1058 Version: 22.3.4 (serverType: BUNGEE)
 - BedWarsProxy Version: 1.2.4 by Mher
 - Cosmetics Addon: 1.0.0

**Comment by MherZaqaryan** [comment]
This issue is already fixed and should be available in the next update!
