### ISSUE TITLE
[Bug] Empty Spray Page 3

### ISSUE THREAD

**Issue by Caily-E** [MherZaqaryan/BedWars1058-Cosmetics-Issues#60]
**Describe the bug**
The 3rd page in the Sprays cosmetics is empty.

**How to reproduce**
1. Open the cosmetics menu
2. Click on Sprays and go to 3rd page 
3. it will be empty with no extra spray on that page

**Screenshots**
https://imgur.com/SCQ7V8F

**Server Information (please complete the following information):**
 - OS: Linux
 - Server Software: CarbonSpigot
 - Software Version: 1.8.8
 - BedWars1058 Version: 22.7
 - Cosmetics Addon: 1.0.3-BETA

**Comment by MherZaqaryan** [comment]
This issue has been fixed and will be available in the next update!
