### ISSUE TITLE
NPC's Hologram Duplication When "always-use-name-holograms: true" Is Set To True In Citizens Config 

### ISSUE THREAD

**Issue by Caily-E** [MherZaqaryan/BedWars1058-Cosmetics-Issues#61]
**Describe the bug**
When we set "always-use-name-holograms: true" in citizens config the NPC hologram duplicates when we come close to it 

**How to reproduce**
1. Set "always-use-name-holograms: true" in citizens config and restart
2. Then join the server and queue for a arena 
3. Then check NPC's and come closer to it the word "RIGHT CLICK" will duplicate

**Screenshots**
When we are at a further distance form the NPC:
https://imgur.com/WJo1C3n
When we are at a closer distance from the NPC: 
https://imgur.com/k18tExO

**Server Information (please complete the following information):**
 - OS: Linux
 - Server Software: CarbonSpigot
 - Software Version: 1.8.8
 - BedWars1058 Version: 22.7
 - Cosmetics Addon: 1.0.3-BETA

**Comment by MherZaqaryan** [comment]
Hey, I've just confirmed that this is a client-sided issue, please try using the vanilla Minecraft to see if it still appears.

**Comment by Caily-E** [comment]
Fixed this issue by using Citizens version Citizens-2.0.29-b2447
