### ISSUE TITLE
[Bug] Incompatibility with Parties Plugin by Alessio

### ISSUE THREAD

**Issue by SameshB** [MherZaqaryan/BedWars1058-Cosmetics-Issues#63]
**Describe the bug**

**How to reproduce**
1. Install Bedwars1058 22.7
2. Install Bedwars1058Cosmetics1.0.3-Beta
3. Install Parties by Alessio 3.2.6 and LastLoginApi 1.7.3
4. Have the server online with ~8-10 players minimum
5. Play a few bedwars matches in the server. (Optional, might not be needed)
6. Try to /party invite <TAB Complete>. 
7. You will see that /party invite doesn't show all online players. If you write in the player's name manually, it says "You can only invite online players."

**Screenshots**
3min recording sent in Discord dms (SameshB#7290)

**Server Information**
 - Server Software: CarbonSpigot 3.1.1
 - Software Version: 1.8.9
 - BedWars1058 Version: 22.7
 - Cosmetics Addon: 1.0.3-Beta

**Comment by MherZaqaryan** [comment]
Thanks for reporting, your issue is currently being resolved.

**Comment by MherZaqaryan** [comment]
This issue has been marked as a false after a couple of times of reproduction.
