### ISSUE TITLE
[Bug] Free BridgeEgg with Hatching Eggs final kill effect.

### ISSUE THREAD

**Issue by GyroGyro** [MherZaqaryan/BedWars1058-Cosmetics-Issues#64]
**Describe the bug**
Using the final kill effect Hatching Eggs it is possible to collect some eggs and when they are thrown they work like bedwars1058's Bridge Egg.
in a nutshell, using when effect you can get the Bridge Eggs for free.

**How to reproduce**
1. Select Hatching Eggs final kill effect 
2. Kill someone (final kill)
3. You can collect the eggs and use them as a bridge egg

**Screenshots**
https://youtu.be/VW6wkPmyHbw

**Server Information (please complete the following information):**
 - OS: Linux
 - Server Software: NachoSpigot
 - Software Version: 1.8.9
 - BedWars1058 Version: 22.3 (Compiled from GitHub)
 - Cosmetics Addon: 1.0.3

**Comment by MherZaqaryan** [comment]
Thanks for reporting this issue! We will be back with an update soon!

**Comment by MherZaqaryan** [comment]
This issue has been fixed and will be available in the next update.
