### ISSUE TITLE
[Bug] Error trying to open the shopkeepers menu

### ISSUE THREAD

**Issue by Askarionn** [MherZaqaryan/BedWars1058-Cosmetics-Issues#65]
**Describe the bug**
Can't open the shopkeepers menu

**How to reproduce**
1. Don't know exactly

**Screenshots**
https://pastebin.com/e1K5MBG4

**Server Information (please complete the following information):**
 - OS: Linux
 - Server Software: PandaSpigot
 - Software Version: 1.8.8
 - BedWars1058 Version: Proxy 1.2.4
 - Cosmetics Addon: 1.0.3

**Additional context**

**Comment by MherZaqaryan** [comment]
Thanks for reporting this issue! Please include the reproducing steps if possible.

**Comment by MherZaqaryan** [comment]
According to the error, this issue is not related to the shopkeeper menu, I will try finding the real reason for this happening. In the meantime please double-check it.
