### ISSUE TITLE
[Feature Request] A way to make cosmetics accessible to buy with specific permission.

### ISSUE THREAD

**Issue by PacificDriver** [MherZaqaryan/BedWars1058-Cosmetics-Issues#66]
Combined conditions: To get cosmetics you need to have a certain entitlement + spend coins.

Example: you are a player, you cannot buy a certain cosmetic solution because you don't have the permission's to do so, but if you have the permission's, you buy that cosmetic with accumulated game coins!

**Comment by MherZaqaryan** [comment]
Thanks for the feature request! For now, this feature request is accepted.

**Comment by MherZaqaryan** [comment]
This feature request has been implemented and will be available in the next update, the complete documentation about how to use it will be available with the release.
