### ISSUE TITLE
[Bug] Cosmetics problem in Victory dances category

### ISSUE THREAD

**Issue by PacificDriver** [MherZaqaryan/BedWars1058-Cosmetics-Issues#68]
**Describe the bug**
After applying these cosmetics, nothing happens.

- [x] Anvil Rain
- [x] Cold Snap
- [x] Twerk Apocalypse

**How to reproduce**
1. Open the Victory Dances menu.
2. Choose the Anvil Rain victory dance.
3. Try using it in-game.
4. And it will not work.
5. Repeat the same with Cold Snap and Twerk Apocalypse victory dance.

**Additional Information**
No info.

**Server Information (please complete the following information):**
- OS: ubuntu 20
- Server Software: Paper
- Software Version: 1.17.1
- BedWars1058 Version: 22.7
- Cosmetics Addon: 1.1.3 beta

**Comment by MherZaqaryan** [comment]
Thanks for reporting this issue! We will be back with an update soon!

**Comment by MherZaqaryan** [comment]
Update 1: The issue with the Anvil Rain victory dance is now fixed.

**Comment by MherZaqaryan** [comment]
Update 2: The issue with the Cold Snap victory dance is now fixed.

**Comment by MherZaqaryan** [comment]
Update 3: There were no issues with Twerk Apocalypse, the Citizens plugin wasn't installed.

**Comment by MherZaqaryan** [comment]
This issue has been fully fixed, and will be available in the next update!
