### ISSUE TITLE
[Bug] Cosmetics problem in Final Kill Effects: category

### ISSUE THREAD

**Issue by PacificDriver** [MherZaqaryan/BedWars1058-Cosmetics-Issues#69]
**Describe the bug**
After applying these cosmetics, nothing happens.

- [x] Blood Explosion
- [x] Shattered
- [x] Cow Rocket

**How to reproduce**
1. Open the Final Kill Effect menu.
2. Choose Blood Explosion kill effect.
3. Try using it in-game.
4. And it will not work.
5. Repeat the same with Shattered and Cow Rocket final kills.

**Additional Information**
Console error for Cow Rocket: https://sourceb.in/wYShywEm9s

**Server Information (please complete the following information):**
- OS: ubuntu 20
- Server Software: Paper
- Software Version: 1.17.1
- BedWars1058 Version: 22.7
- Cosmetics Addon: 1.1.3 beta

**Comment by MherZaqaryan** [comment]
Thanks for reporting this issue! We will be back with an update soon!

**Comment by MherZaqaryan** [comment]
Update 1: After reviewing the issue, the Blood Explosion and Shattered final kill, can't work on non-legacy versions. Thus, the final kills have been marked as legacy cosmetics and will only work on legacy server versions.

**Comment by MherZaqaryan** [comment]
Update 2: This issue with the Cow Rocket effect has already been fixed and should be available in the next update.
