### ISSUE TITLE
Command to remove all cosmetics

### ISSUE THREAD

**Issue by SpiziTV** [MherZaqaryan/BedWars1058-Cosmetics-Issues#7]
I would like a command which remove all cosmetics when done

In this case, we can use the "back" button of the main menu to set the remove cosmetics command on it

**Comment by MherZaqaryan** [comment]
I would need more information about this request it seems confusing.

**Comment by SpiziTV** [comment]
This function would be a command that the player can execute from the chat or from an item on the main cosmetics menu
When he right-clicks on the item defined for example, this will have the effect of selecting the default cosmetics for all categories instead of the cosmetics he had selected
So that you don't have to set the default cosmetics manually for each category

**Comment by MherZaqaryan** [comment]
This feature request was accepted, has been implemented, and should be available in the next 1.0.1 update!
