### ISSUE TITLE
[Bug] Cosmetics problem in Bed Destroyed: category

### ISSUE THREAD

**Issue by PacificDriver** [MherZaqaryan/BedWars1058-Cosmetics-Issues#71]
**Describe the bug**
After applying these cosmetics, nothing happens.

- [x] Lava Explosion
- [x] Thief
- [x] Lady Bug

**How to reproduce**

1. Open the Bed Destroy menu.
2. Choose Lava Explosion bed destroy.
3. Try using it in-game.
4. And it will not work.
5. Repeat the same with Thief and Lady Bug bed destroys.

**Additional Information**
Console error for Thief: https://sourceb.in/zyTrvpc6vh
Console error for Lady Bug: https://sourceb.in/qCVOjssaRV

**Server Information (please complete the following information):**

- OS: ubuntu 20
- Server Software: Paper
- Software Version: 1.17.1
- BedWars1058 Version: 22.7
- Cosmetics Addon: 1.1.3 beta

**Comment by MherZaqaryan** [comment]
Thanks for reporting this issue! We will be back with an update soon!

**Comment by MherZaqaryan** [comment]
Update 1: After reviewing the issue, the Lava Explosion bed destroy, can't work on non-legacy versions. Thus, the bed destroy has been marked as a legacy cosmetic and will only work on legacy server versions.

**Comment by MherZaqaryan** [comment]
Update 2: The issue with Thief effect has already been fixed and should be available in the next update.

**Comment by MherZaqaryan** [comment]
Update 3: The issue with the Lady Bug effect has already been fixed and should be available in the next update.
