### ISSUE TITLE
[Bug] Sprays are all wrong 

### ISSUE THREAD

**Issue by foo1ishh** [MherZaqaryan/BedWars1058-Cosmetics-Issues#72]
**Describe the bug**
What ever I choose from sprays, it will just give me a random one (the wrong one). For example, if I choose Santa, it will give me the ox one. That’s very strange 

**How to reproduce**
1. Choose a spray in lobby (Not a hypixel logo one, as idk why only that one works)
2. Join a game and click the item frame
3. The sprays are not matched

**Screenshots**

**Server Information (please complete the following information):**
 - OS: window
 - Server Software: paper 
 - Software Version: 1.8.8
 - BedWars1058 Version: latest version downloaded from polymart
 - Cosmetics Addon: 1.0.3 Beta build

**Additional context**

**Comment by MherZaqaryan** [comment]
This issue is now fixed and will be available in the next update!
