### ISSUE TITLE
[Bug] Island Topper facing wrong directions

### ISSUE THREAD

**Issue by vicente1313** [MherZaqaryan/BedWars1058-Cosmetics-Issues#76]
Island Toppers are facing the wrong direction

**How to reproduce**
1. Setup the island toppers in a arena
2. Go to the lobby
3. Select an island topper
4. Join an arena
5 Will result in island toppers facing wrong directions

**Screenshots**
![image](https://user-images.githubusercontent.com/125751583/219874426-a1b0796f-056b-42d5-9708-e8f3b3df8b3b.png)

**Server Information :**
 - OS: Windows
 - Server Software: Spigot
 - Software Version: 1.8.8
 - BedWars1058 Version: 22.3.4
 - Cosmetics Addon: 1.1.0

**Comment by MherZaqaryan** [comment]
This issue is already fixed and will be available in the next update.
