### ISSUE TITLE
[Bug]An error occurred when opening some menus in version 1.12.2

### ISSUE THREAD

**Issue by PixelEast** [MherZaqaryan/BedWars1058-Cosmetics-Issues#77]
**Describe the bug**
An error occurred when opening some menus in version 1.12.2 .
For example, the Island Toppers menu and the third page of the Spreads menu.

error log:
https://pastebin.com/nN1yxC8c

**Server Information (please complete the following information):**
 - OS: Windows Server
 - Server Software: Paper
 - Software Version: 1.12.2
 - BedWars1058 Version: BedwarsProxy-1.2.4-PAF-1.19Support
 - Cosmetics Addon: 1.1.1

**Comment by MherZaqaryan** [comment]
This issue has already been resolved, and the following update will include it!
