### ISSUE TITLE
[Feature Request]Making Shopkeeper Skin and Island Topper category to load (for selecting or buying only) even if Citizens or FAWE isn't available.

### ISSUE THREAD

**Issue by PixelEast** [MherZaqaryan/BedWars1058-Cosmetics-Issues#78]
Making Shopkeeper Skin and Island Topper category to load (for selecting or buying only) even if Citizens or FAWE isn't available.

Because my lobby server uses other NPC plugins(Adyeshach), it does not use Citizens, resulting in the inability to load the Shopkeeper Skin category.

**Comment by MherZaqaryan** [comment]
This feature request has been implemented, and the following update will include it!
