### ISSUE TITLE
[Bug]Using the Search feature can cause players to disconnect

### ISSUE THREAD

**Issue by PixelEast** [MherZaqaryan/BedWars1058-Cosmetics-Issues#79]
**Describe the bug**
Using the Search feature can cause players to disconnect

Every time I use the search function and click Finish or ESC on the sign input menu, no matter what I type, I don't type anything at all, the player will be disconnected

console message:
https://pastebin.com/XtaktHc2

**Server Information (please complete the following information):**
 - OS: Windows Server
 - Server Software: Paper
 - Software Version: 1.12.2
 - BedWars1058 Version: BedwarsProxy-1.2.4-PAF-1.19Suppor
 - Cosmetics Addon: 1.1.1

**Comment by PixelEast** [comment]
![GIF 2023-3-21 16-46-42](https://user-images.githubusercontent.com/30312760/226556265-dce7cc3a-cc8b-4f4f-8363-40675a1d2c03.gif)

**Comment by MherZaqaryan** [comment]
This issue has already been resolved, and the following update will include it!
