### ISSUE TITLE
Glowing effect on selected cosmetic

### ISSUE THREAD

**Issue by SpiziTV** [MherZaqaryan/BedWars1058-Cosmetics-Issues#8]
It can be cool if you add an option of glowing effect on selected cosmetics
So if i choose "Pigsplosion" it will have a glowing effect on the menu to show me that's the cosmetic i actually have :)

Thanks in advance

**Comment by MherZaqaryan** [comment]
This feature request is rejected, because the cosmetics icon could be enchanted from configuration!
