### ISSUE TITLE
[Bug]Error searching

### ISSUE THREAD

**Issue by PixelEast** [MherZaqaryan/BedWars1058-Cosmetics-Issues#80]
https://pastebin.com/g4vKKUrp
The content I search for is the default spray I modified
This error will occur when searching for any character in "像素东方Logo" 
![image](https://user-images.githubusercontent.com/30312760/227521981-bcdc99f5-95f0-4b02-8b5a-24730c5e04b0.png)

**Comment by MherZaqaryan** [comment]
This issue has already been resolved, and the following update will include it!
