### ISSUE TITLE
[Feature Request]Improvement of spray hologram

### ISSUE THREAD

**Issue by PixelEast** [MherZaqaryan/BedWars1058-Cosmetics-Issues#81]
Let the hologram below the spray always appear in the game, rather than disappear 1 minute after the game starts.
![%JVLJ%R09%_~788{FFGE GA](https://user-images.githubusercontent.com/30312760/227522589-4933101b-437e-452a-b8ca-6ebd7ca9113e.png)

**Comment by MherZaqaryan** [comment]
This feature request has been implemented, and the following update will include it!
