### ISSUE TITLE
[Bug]Default configuration for shopkeeper skin incorrect

### ISSUE THREAD

**Issue by PixelEast** [MherZaqaryan/BedWars1058-Cosmetics-Issues#82]
![image](https://user-images.githubusercontent.com/30312760/227534418-16b8721a-9d7b-451b-be3e-fe987ac6817f.png)
The type of snowman should be ENTITY instead of SYSTEM

**Comment by MherZaqaryan** [comment]
This issue has already been resolved, and the following update will include it!
