### ISSUE TITLE
[Bug] Snowplosion issue

### ISSUE THREAD

**Issue by ImYenil** [MherZaqaryan/BedWars1058-Cosmetics-Issues#83]
**Describe the bug**
snowplosion final kill effect doesn't trigger properly

**How to reproduce**
1. It happens when you select the snowplosion final kill effect and perform a final kill.

**Screenshots**
X

**Server Information (please complete the following information):**
 - OS: [e.g. Linux, Windows] Windows
 - Server Software: [e.g. Paper, Spigot] Paper
 - Software Version: [e.g. 1.8.9] 1.8.9
 - BedWars1058 Version: [e.g. 21.10.1] 23.2.1
 - Cosmetics Addon: [e.g. 1.1.1] 1.1.2

**Additional context**
https://pastebin.com/h0n2BvGx

**Comment by MherZaqaryan** [comment]
This issue is already fixed, and will be available in the next update!
