### ISSUE TITLE
[Bug]Search title translation doesn't work

### ISSUE THREAD

**Issue by PixelEast** [MherZaqaryan/BedWars1058-Cosmetics-Issues#85]
![8O6RS)Z`X4BXO~4SUR2~$ZE](https://user-images.githubusercontent.com/30312760/227729549-de43c734-f303-4e7f-8d63-1ef6c02050a4.png)
![~SUR I)Z%@46D9JRFEU7I35](https://user-images.githubusercontent.com/30312760/227729563-3d25bc86-2eea-48fb-a03f-380d47118a53.png)

**Comment by MherZaqaryan** [comment]
This issue is already fixed, and will be available in the next update!
