### ISSUE TITLE
[Bug] Projectile tails will not be cleared

### ISSUE THREAD

**Issue by PixelEast** [MherZaqaryan/BedWars1058-Cosmetics-Issues#86]
when using snowballs, fireball, and ender pearls, the projectile tails will not be cleared
![WENIEY6 O_P95AY006IR@N1](https://user-images.githubusercontent.com/30312760/227729614-d42a281a-8c5f-4114-9fc9-8ef9e4a420c8.png)

**Comment by MherZaqaryan** [comment]
This issue is already fixed and will be available in the next update!
