### ISSUE TITLE
[Feature Request]Attributes that can hide some icons in the menu

### ISSUE THREAD

**Issue by PixelEast** [MherZaqaryan/BedWars1058-Cosmetics-Issues#88]
Attributes that can hide some icons in the menu ect these:
![image](https://user-images.githubusercontent.com/30312760/227785991-5e9b971b-ae9b-46ae-8bef-cfa91973a9aa.png)
![image](https://user-images.githubusercontent.com/30312760/227786029-0adf6855-deda-4b49-8e5c-30590fbd024e.png)
![image](https://user-images.githubusercontent.com/30312760/227786055-04003a8c-2995-44b8-83c8-0c01d07faf14.png)
![image](https://user-images.githubusercontent.com/30312760/227786085-3ec0a226-e6af-4410-87fa-ed13cd07df28.png)

**Comment by mingasdf** [comment]
这是原版自带的,改不了。 你可以尝试修改原版客户端来隐藏

**Comment by PixelEast** [comment]
> 这是原版自带的,改不了。 你可以尝试修改原版客户端来隐藏

这是可以被隐藏的

**Comment by mingasdf** [comment]
搜了下wiki,确实可以用nbt改 就看mher会不会去改了。

**Comment by MherZaqaryan** [comment]
This issue is already fixed, and will be available in the next update!
