### ISSUE TITLE
[Feature Request] Citizens Skin layers feature

### ISSUE THREAD

**Issue by ImYenil** [MherZaqaryan/BedWars1058-Cosmetics-Issues#89]
**Is your feature request related to a problem? Please describe.**
Due to citizens version update, you need to add skin layers manually. Is it possible to add? Because of shopkeeper skins

**Describe the solution you'd like**
the code
this.npc.addTrait(SkinLayers.class);

**Comment by MherZaqaryan** [comment]
This feature request was implemented and it will be available in the next update!
