### ISSUE TITLE
Anvil Rain/Raining Pigs Issue

### ISSUE THREAD

**Issue by NeosKing108** [MherZaqaryan/BedWars1058-Cosmetics-Issues#9]
**Describe the bug**
When you use Anvil Rain and Raining Pigs the dance starts with a delay

**How to reproduce**
1. Select Anvil Rain or Raining Pigs
2. Win a game
3. Before dance starting there are like 10 seconds of server "freeze"

**Screenshots**
Yt Video: https://youtu.be/jsQiSp1CW3o

**Server Information (please complete the following information):**
 - OS: [Linux]
 - Server Software: [Paper]
 - Software Version: [1.8.8]
 - BedWars1058 Version: [22.3.4]
 - Cosmetics Addon: [1.0.0]

**Additional context**

**Comment by NeosKing108** [comment]
Server's informations
- Ryzen 9 3900x (6 core)
- 16gb ram ddr4 (3200mhz) -> 14 dedicated to server

**Comment by MherZaqaryan** [comment]
This performance issue is fixed but not tested, and will be available on the next update!
