### ISSUE TITLE
[Feature Request]ShopkeeperSkin Improvement

### ISSUE THREAD

**Issue by PixelEast** [MherZaqaryan/BedWars1058-Cosmetics-Issues#90]
When there are multiple players in the team, apply the ShopkeeperSkin selected by two random players to the Shop and Upgrade, respectively

**Comment by MherZaqaryan** [comment]
Hey! Unfortunately, this feature request cannot be fulfilled because it will only function for doubles and will be incompatible with other modes. Even if I only do it for doubles mode, I'll have to completely rewrite the shopkeeper skin system.
