### ISSUE TITLE
[Feature Request] Dragon-rider of victory dance will not destroy the map

### ISSUE THREAD

**Issue by PixelEast** [MherZaqaryan/BedWars1058-Cosmetics-Issues#91]
**Describe the bug**
It seems that the EnderDragon will not destroy the map
When I win, I just ride on a dragon and get stuck and wait for the game to end

**Server Information (please complete the following information):**
 - OS: Windows Server
 - Server Software: Paper
 - Software Version: 1.12.2
 - BedWars1058 Version: 23.3
 - Cosmetics Addon: 1.1.2

**Comment by MherZaqaryan** [comment]
This was reported as a bug, however it's a feature request. This feature request has been added and it will be available in the next update
