### ISSUE TITLE
[Bug] Spray hologram disappears while playing the game

### ISSUE THREAD

**Issue by ImYenil** [MherZaqaryan/BedWars1058-Cosmetics-Issues#92]
**Describe the bug**
Spray hologram disappears while playing the game

**How to reproduce**
Spray hologram disappears while playing

**Screenshots**

**Server Information (please complete the following information):**
 - OS: [e.g. Linux, Windows] Windows
 - Server Software: [e.g. Paper, Spigot] Paper
 - Software Version: [e.g. 1.8.9] 1.8.9
 - BedWars1058 Version: [e.g. 21.10.1] 23.3-SNAPSHOT
 - Cosmetics Addon: [e.g. 1.1.1] 1.1.2

**Additional context**

**Comment by MherZaqaryan** [comment]
This is not a bug, this is a feature, by default the hologram will disappear after 60 seconds, you can adjust it from the configuration file's `categories.spray.hologram-expiry`, if you wish to make it not disappear then set it to 0.
