### ISSUE TITLE
[Bug]It will change to "None" after a while after selection

### ISSUE THREAD

**Issue by NewPixelDev** [MherZaqaryan/BedWars1058-Cosmetics-Issues#93]
**Describe the bug**
For example, if I choose "A effect", after a period of time, it will become "None" inexplicably

**How to reproduce**
You only need to choose a special effect at random, and it will automatically become "none" after a while

**Screenshots**
None (because there is no error, no prompt)

**Server Information (please complete the following information):**
 - OS: Windows
 - Server Software: Paper1.8.8-445
 - Software Version: 1.8.8
 - BedWars1058 Version: 22.3.4.
 - Cosmetics Addon: 1.1.2
 
**Additional context**
This problem is simply that the selected "special effect" will be automatically changed to "none"

**Comment by PixelEast** [comment]
+1

**Comment by MherZaqaryan** [comment]
This issue is already fixed, and will be available in the next update!

**Comment by NewPixelDev** [comment]
Please when will it be updated, I can't wait haha

**Comment by PixelEast** [comment]
> Please when will it be updated, I can't wait haha

I also hope to receive the update as soon as possible, but Mher has encountered some issues in her personal life. Perhaps this update won't arrive so soon. Good luck to Mher
