### ISSUE TITLE
[Bug] Final kill snowplosion cosmetic issues

### ISSUE THREAD

**Issue by PixelEast** [MherZaqaryan/BedWars1058-Cosmetics-Issues#95]
Server version: Paper 1.12.2
Snow on the ground will not be automatically cleared, and if snow is generated on incomplete blocks, it will cause players to be stuck and unable to move.
I think it's necessary to only generate snow on the complete block
![(V MZO6E_C9HZN)BJ2 HB1M](https://user-images.githubusercontent.com/30312760/233792230-bf3bd8b5-946f-456b-841f-5e9d1f8cf808.png)
![05C%DEJ6VNU`BIL7@4_G@IC](https://user-images.githubusercontent.com/30312760/233792237-eb5f13b5-bf20-4795-95d2-a823ec95e020.png)
![GIF 2023-4-22 22-56-38](https://user-images.githubusercontent.com/30312760/233792245-0e6a7092-48da-49d6-86c3-9303026086a3.gif)
![GIF 2023-4-22 22-57-58](https://user-images.githubusercontent.com/30312760/233792252-e4ae7bc8-9983-40f0-a4de-26711a8942eb.gif)

**Comment by MherZaqaryan** [comment]
Thanks for reporting! This issue is fixed and will be available in the next update!
