### ISSUE TITLE
[Bug] sometimes all cosmetic items selected by the player are set to NONE

### ISSUE THREAD

**Issue by ImYenil** [MherZaqaryan/BedWars1058-Cosmetics-Issues#96]
**Describe the bug**
sometimes all cosmetic items selected by the player are set to NONE

**How to reproduce**
This seems to happen randomly

**Screenshots**
none

**Server Information (please complete the following information):**
 - OS: [e.g. Linux, Windows] Windows 
 - Server Software: [e.g. Paper, Spigot] Paper
 - Software Version: [e.g. 1.8.9] 1.8.9
 - BedWars1058 Version: [e.g. 21.10.1] 23.3-SNAPSHOT
 - Cosmetics Addon: [e.g. 1.1.1]  1.1.2

**Additional context**
I didn't touch anything related to the database.

**Comment by NewPixelDev** [comment]
+1

**Comment by MherZaqaryan** [comment]
This issue is already fixed, and will be available in the next update!
