### ISSUE TITLE
[Feature Request] shopkeeper skin mob slient

### ISSUE THREAD

**Issue by ImYenil** [MherZaqaryan/BedWars1058-Cosmetics-Issues#99]
**Is your feature request related to a problem? Please describe.**
bedwars1058 default villagers spawn with no ai and slient. but, when using this addon, the shopkeeper skin does not become slient.

**Describe the solution you'd like**
I wish mobs were added to spawn in a slient state

**Describe alternatives you've considered**
Add mobs to spawn in a slient state

**Additional context**

**Comment by ImYenil** [comment]
this.npc.data().setPersistent(NPC.Metadata.SILENT, true);

I have provided the code here

**Comment by MherZaqaryan** [comment]
Thanks for reporting, this issue is fixed, and will be available in the next update!

The suggested code seemed to work, I tested it on 1.8.9!
